//! `lain schema` subcommand — emit the canonical tool schema dump.
//!
//! Defect D-L2: there was no central, machine-readable artifact that
//! listed every tool `tools/list` serves. The on-disk file produced
//! here is regenerated by `make schema` and committed; a CI step
//! (`make schema && git diff --exit-code docs/tool-schema.json`) keeps
//! it in lock-step with the protocol.

use anyhow::{Context, Result};
use clap::Subcommand;
use std::path::PathBuf;

/// Subcommands for `lain schema`. The dump is the only verb today;
/// `validate` and `diff` are anticipated future siblings.
#[derive(Debug, Subcommand)]
pub enum SchemaAction {
    /// Write the canonical `tools/list` payload to a JSON file.
    /// Default path: `./docs/tool-schema.json`.
    Dump {
        /// Output file path. Parent directories are created if missing.
        #[arg(long, default_value = "./docs/tool-schema.json")]
        out: PathBuf,
    },
}

/// Dispatch a `lain schema <action>` invocation.
pub fn run(action: SchemaAction) -> Result<()> {
    match action {
        SchemaAction::Dump { out } => dump(&out),
    }
}

/// `lain schema dump [--out PATH]` — serialize the live `tools/list`
/// surface and write it as a pretty-printed JSON array.
///
/// We instantiate a stub NLP embedder (no model needed) so the
/// `inert_tool_names` filter mirrors what `tools/list` does on the
/// server side. Without this filter the dump would advertise
/// `semantic_search` even when the embedder is a stub, while
/// `tools/list` would not — drift on every CI run.
fn dump(out: &std::path::Path) -> Result<()> {
    let embedder = crate::server::nlp::NlpEmbedder::new_with_threads(0)
        .context("init stub embedder for schema dump")?;
    let inert = crate::server::mcp::handler::inert_tool_names(&embedder);
    let tools = crate::server::mcp::definitions::dump_tools_schema(inert);
    let pretty = serde_json::to_string_pretty(&tools)
        .context("serialize schema dump")?;
    if let Some(parent) = out.parent() {
        if !parent.as_os_str().is_empty() {
            std::fs::create_dir_all(parent)
                .with_context(|| format!("create parent dir {}", parent.display()))?;
        }
    }
    std::fs::write(out, pretty.as_bytes())
        .with_context(|| format!("write {}", out.display()))?;
    println!("Wrote {} tools to {}", tools.len(), out.display());
    Ok(())
}
