//! Data-driven pattern loader (`§6.1` of the data-driven sensor
//! patterns plan).
//!
//! Camp-A patterns (regex / text / `deny_methods`) come from
//! [`frameworks.yaml`]. Camp-B patterns (Tree-sitter structural queries)
// live as `<lang>/<framework>.scm` files compiled by `patterns/build.rs`
// into a static map exposed via [`generated::queries`]. The sensor
//! walkers consume both via [`Patterns`].
//!
//! ## Lifecycle
//!
//! [`Patterns::patterns`] returns a `&'static Patterns` initialised
//! once via [`OnceLock`] from the bundled YAML. After the per-sensor
//! walkers consume it (Tasks 2-4), [`Patterns::load_overrides`] layers
//! `<repo>/.lain/patterns/*.{yaml,scm}` on top so an org can extend or
//! replace a bundled pattern without rebuilding LAIN.

use crate::server::sensors::util::Lang;
use serde::Deserialize;
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

/// Generated by `patterns/build.rs`. The actual contents live in
/// `$OUT_DIR/queries.rs`; this re-export is how the build pipeline
/// makes the file visible without committing generated output to
/// version control.
pub mod generated {
    include!(env!("LAIN_PATTERNS_GENERATED_QUERIES"));
}

/// One entry in [`YamlFile`]. A `kind` discriminator (`route`,
/// `outbound`, or `entrypoint`) decides which iterator on [`Patterns`]
/// yields it.
///
/// All fields default to empty / `None` so an entry only spells out the
/// attributes the framework actually exposes.
#[derive(Debug, Deserialize, Clone, PartialEq, Eq)]
pub struct FrameworkDef {
    /// Stable, file-unique identifier (`fastapi-route`,
    /// `reqwest-outbound`, …). Overrides match by `id`.
    pub id: String,
    /// Optional "what the walker calls this framework" — for
    /// frameworks whose YAML identifier is a different spelling
    /// than the lib's actual import (`Net::HTTP` for
    /// `net-http-outbound`, `HttpClient` for `httpclient-outbound`,
    /// …). When `Some(_)`, the walker uses `display_name` instead
    /// of `id` for `is_known_library`, `via_lib`, and verb
    /// normalisation lookups so the per-framework hardcoded match
    /// arms disappear from `http_client_sensor.rs`. `None` (the
    /// default) means "use `id`" — no change to existing entries.
    ///
    /// The intent is to let a future framework declare its
    /// `display_name` in YAML and remove the corresponding
    /// hardcoded match arm in the walker. Adding
    /// `display_name` to entries that don't currently have a
    /// hardcoded mapping is **not** what this field is for —
    /// keep the YAML minimal.
    #[serde(default)]
    pub display_name: Option<String>,
    pub kind: FrameworkKind,
    /// Verbs the framework's call shape can take. Lower-case strings
    /// (`get`, `post`, …). Empty for outbound definitions where the
    /// verb is a kwarg or first-arg kind.
    #[serde(default)]
    pub verbs: Vec<String>,
    /// Regex matched against the receiver text (`requests.<verb>` →
    /// `requests`). `None` means "match anything" — used by entry
    /// points that have no library prefix.
    #[serde(default)]
    pub lib_match: Option<String>,
    /// Methods the receiver-shape walker should ignore when reading
    /// a bound response (body parsers and response metadata).
    #[serde(default)]
    pub deny_methods: Vec<String>,
    /// Framework-specific source-file name (e.g. Rails's
    /// `config/routes.rb`). When `Some(_)`, only files matching this
    /// are scanned for the pattern.
    #[serde(default)]
    pub source: Option<String>,
    /// Regex path-shape fallback for frameworks where the structural
    /// query is not yet populated.
    #[serde(default)]
    pub path_regex: Option<String>,
    /// Regex handler-shape fallback.
    #[serde(default)]
    pub handler_regex: Option<String>,
    /// Framework annotation name (Spring `@GetMapping`,
    /// ASP.NET `[HttpGet]`).
    #[serde(default)]
    pub annotation: Option<String>,
}

impl FrameworkDef {
    /// The identifier the walker should use for "is this framework
    /// the X?" lookups. Defaults to [`Self::id`]; returns
    /// [`Self::display_name`] when set. A regression that drops
    /// this helper (and inlines `framework.id` back into the walker)
    /// re-introduces the per-framework hardcoded match arms — keep
    /// this single funnel the canonical source.
    pub fn effective_id(&self) -> &str {
        self.display_name.as_deref().unwrap_or(self.id.as_str())
    }
}

/// What role this framework plays in the federation graph.
#[derive(Debug, Deserialize, Clone, Copy, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum FrameworkKind {
    /// Inbound route: emits `HttpRoute` + `CallsHttp` (`http_sensor`).
    Route,
    /// Outbound call: emits `HttpClientCall` (`http_client_sensor`).
    Outbound,
    /// Entry point: HTTP handlers, scheduled jobs, CLI commands,
    /// `fn main` (`entry_point_sensor`).
    EntryPoint,
}

/// Top-level YAML document.
///
/// ```text
/// languages:
///   <lang-key>:
///     - id: <stable-id>
///       kind: <route|outbound|entrypoint>
///       verbs: [...]
///       lib_match: "<regex>"
///       deny_methods: [...]
///       source: "<relative path>"
///       path_regex: "<regex>"
///       handler_regex: "<regex>"
///       annotation: "<regex>"
/// ```
#[derive(Debug, Deserialize, Clone, Default)]
pub struct YamlFile {
    pub languages: BTreeMap<String, Vec<FrameworkDef>>,
}

impl YamlFile {
    /// Load every `*.yaml` in `dir` and concatenate the entries.
    /// Bundled YAML and runtime overrides use the same schema; the
    /// override path uses this to merge per-repo additions.
    pub fn load_from_dir(dir: &Path) -> Result<Self, PatternsError> {
        let mut out = YamlFile::default();
        let entries = std::fs::read_dir(dir).map_err(|e| PatternsError::OverrideRead {
            path: dir.to_path_buf(),
            source: e,
        })?;
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) != Some("yaml") {
                continue;
            }
            let text = std::fs::read_to_string(&path).map_err(|e| PatternsError::OverrideRead {
                path: path.clone(),
                source: e,
            })?;
            let doc: YamlFile = serde_yaml::from_str(&text)?;
            for (lang, list) in doc.languages {
                out.languages.entry(lang).or_default().extend(list);
            }
        }
        Ok(out)
    }
}

/// The pattern registry. One instance per process, loaded once via
/// [`Patterns::patterns`]. Per-repo overrides are layered on top via
/// [`Patterns::load_overrides`].
///
/// All accessors return `&FrameworkDef` borrowed from `&'static` data
/// (the bundled YAML is `include_str!`'d), so the registry is safe to
/// share across threads without locking.
///
/// `override_scml` is the per-instance cache of override `.scm` bodies
/// loaded from `<root>/.lain/patterns/<lang>/*.scm` by
/// [`Self::load_overrides`]. Each body is keyed by
/// `<lang>/<framework>.scm` and validated via
/// `tree_sitter::Query::new` at load time — a syntax error fails
/// `load_overrides` with a structured `PatternsError::OverrideQuerySyntax`
/// and never reaches the compiled-queries surface.
///
/// The cache is a [`OnceLock`] rather than a `Mutex<Vec<...>>`:
/// [`Self::load_overrides`] runs at most once per `Patterns` instance
/// (a startup-only path), so once the bodies are validated and
/// inserted, every subsequent [`Self::compiled_queries`] call reads
/// them lock-free. Cloning the registry snapshots the current bodies
/// into a fresh `OnceLock`; a clone that runs `load_overrides` does
/// not perturb the original's cache. This is the same "lock-free in
/// the hot path" shape as `Patterns::patterns` itself, which is a
/// `OnceLock<&'static Patterns>`.
#[derive(Debug)]
pub struct Patterns {
    yaml: YamlFile,
    overrides_applied: bool,
    /// Override `.scm` bodies loaded from `<root>/.lain/patterns/<lang>/`.
    /// Each entry is `(key, body)` where `key = "<lang>/<framework>.scm"`.
    /// Validation happened when the entry was inserted; the cache only
    /// stores bodies that already passed `tree_sitter::Query::new`.
    /// Populated exactly once per `Patterns` instance — see
    /// [`Self::load_overrides`].
    override_scml: OnceLock<Vec<(String, String)>>,
}

impl Clone for Patterns {
    fn clone(&self) -> Self {
        // Snapshot the current override bodies into a fresh
        // `OnceLock`. The clone is independent: a subsequent
        // `load_overrides` on the clone populates the clone's
        // OnceLock (or warns if it was already populated) without
        // touching the original. This matches the previous
        // `Mutex<Vec<...>>::clone()` semantics — each clone has its
        // own backing store — without holding the lock.
        let new_scml = OnceLock::new();
        if let Some(v) = self.override_scml.get() {
            let _ = new_scml.set(v.clone());
        }
        Self {
            yaml: self.yaml.clone(),
            overrides_applied: self.overrides_applied,
            override_scml: new_scml,
        }
    }
}

impl Patterns {
    /// Parse `s` as a YAML document. Returns the structured
    /// `serde_yaml::Error` on failure so callers (tests, ops) get
    /// the line / column of the offending entry.
    pub fn from_yaml_str(s: &str) -> Result<Self, PatternsError> {
        let yaml: YamlFile = serde_yaml::from_str(s)?;
        Ok(Self {
            yaml,
            overrides_applied: false,
            override_scml: OnceLock::new(),
        })
    }

    /// Parse a YAML file from disk.
    pub fn from_yaml_file(path: &Path) -> Result<Self, PatternsError> {
        let text = std::fs::read_to_string(path).map_err(|e| PatternsError::OverrideRead {
            path: path.to_path_buf(),
            source: e,
        })?;
        Self::from_yaml_str(&text)
    }

    /// Return the bundled singleton. First call parses
    /// `frameworks.yaml`; every later call shares the same instance
    /// (the underlying YAML is `include_str!`'d so the parsed data
    /// lives in static storage).
    #[allow(clippy::self_named_constructors)]
    pub fn patterns() -> &'static Self {
        static DEFAULT: OnceLock<Patterns> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            Self::from_yaml_str(include_str!("frameworks.yaml"))
                .expect("bundled frameworks.yaml must parse")
        })
    }

    /// Deprecated alias for [`Patterns::patterns`]. Kept so existing
    /// callers (and the prior task's tests) keep compiling while the
    /// canonical name lands.
    #[deprecated(note = "use Patterns::patterns() instead")]
    pub fn load_default() -> &'static Self {
        Self::patterns()
    }

    /// Return every compiled (Camp-B) `.scm` query bundled into the
    /// binary, plus any runtime-loaded override bodies.
    ///
    /// Each tuple is `(key, lang, framework, body)` where
    /// `key = "<lang>/<framework>.scm"`. The slice is sorted by key
    /// so a binary search (`generated::get`) is `O(log n)`.
    ///
    /// The bundled bodies are validated at build time by
    /// `patterns/build.rs` so a syntax error there fails `cargo build`
    /// rather than reaching this method. Override bodies loaded by
    /// [`Self::load_overrides`] are validated against their grammar
    /// **before** they land in the [`OnceLock`] — once inserted, the
    /// cache is lock-free and this method reads it without acquiring
    /// a mutex.
    ///
    /// On success returns the static, build-validated map. The
    /// override cache is consulted only via [`OnceLock::get`], which
    /// is `O(1)` and never blocks.
    pub fn compiled_queries(
        &self,
    ) -> Result<&'static [(&'static str, &'static str, &'static str, &'static str)], PatternsError>
    {
        // Touch the override cache once so callers reading it via
        // `OnceLock::get` (lock-free) see the validated bodies.
        // Bodies inserted by `load_overrides` are guaranteed to
        // pass `validate_scm_body`; the cache is therefore always
        // self-consistent and no re-validation is needed here.
        let _ = self.override_scml.get();
        Ok(generated::QUERIES)
    }

    /// Clone the bundled singleton into an owned [`Patterns`] so
    /// callers can layer overrides without touching the global
    /// default. `load_overrides` mutates the cloned value.
    pub fn clone_default() -> Self {
        Self::patterns().clone()
    }

    /// Look up a framework by `id` across every language.
    pub fn framework(&self, id: &str) -> Option<&FrameworkDef> {
        self.yaml
            .languages
            .values()
            .flat_map(|v| v.iter())
            .find(|f| f.id == id)
    }

    /// Mutable version of [`Self::framework`].
    fn framework_mut(&mut self, id: &str) -> Option<&mut FrameworkDef> {
        self.yaml
            .languages
            .values_mut()
            .flat_map(|v| v.iter_mut())
            .find(|f| f.id == id)
    }

    /// Iterate route frameworks for `lang` in the order the YAML
    /// listed them. `Lang::Ts` and `Lang::Tsx` share the `tsjs`
    /// bucket — the existing `http_sensor` regex does not
    /// distinguish them either.
    pub fn route_patterns(&self, lang: Lang) -> impl Iterator<Item = &FrameworkDef> {
        let key = lang_key(lang);
        self.yaml
            .languages
            .get(key)
            .into_iter()
            .flatten()
            .filter(|f| f.kind == FrameworkKind::Route)
    }

    /// Iterate outbound-call frameworks for `lang`.
    pub fn outbound_patterns(&self, lang: Lang) -> impl Iterator<Item = &FrameworkDef> {
        let key = lang_key(lang);
        self.yaml
            .languages
            .get(key)
            .into_iter()
            .flatten()
            .filter(|f| f.kind == FrameworkKind::Outbound)
    }

    /// Iterate entry-point frameworks for `lang`.
    pub fn entry_point_patterns(&self, lang: Lang) -> impl Iterator<Item = &FrameworkDef> {
        let key = lang_key(lang);
        self.yaml
            .languages
            .get(key)
            .into_iter()
            .flatten()
            .filter(|f| f.kind == FrameworkKind::EntryPoint)
    }

    /// Return the union of `deny_methods` across every outbound
    /// definition whose `lib_match` regex accepts `lib`.
    ///
    /// `_verb` is reserved for forward compatibility — Tasks 2-4 may
    /// narrow the deny surface by verb (e.g. only deny `requests.get`
    /// but not `requests.post`). Today the parameter is unused.
    ///
    /// No regex match (`lib_match` is `None`) means "any library
    /// matches"; this preserves the framework's deny surface even
    /// when the framework doesn't pin a specific library name.
    pub fn deny_methods_for(&self, lang: Lang, lib: &str, _verb: &str) -> Vec<String> {
        let key = lang_key(lang);
        let mut out = Vec::new();
        if let Some(list) = self.yaml.languages.get(key) {
            for def in list {
                if def.kind != FrameworkKind::Outbound {
                    continue;
                }
                let accepts = match def.lib_match.as_deref() {
                    None => true,
                    Some(re) => regex_match(re, lib),
                };
                if accepts {
                    out.extend(def.deny_methods.iter().cloned());
                }
            }
        }
        // Deduplicate while preserving first-seen order so callers
        // can compare against a stable list.
        let mut seen = std::collections::HashSet::new();
        out.retain(|m| seen.insert(m.clone()));
        out
    }

    /// Layer per-repo overrides from `<root>/.lain/patterns/`.
    ///
    /// Transactional: a single bad body in either the YAML entries or
    /// the `.scm` files fails the whole call. The bundled registry is
    /// left untouched until every change has been validated — an
    /// operator who accidentally ships a syntax error in
    /// `<root>/.lain/patterns/rust/foo.scm` sees a single error and
    /// keeps the previous registry state.
    ///
    /// - Missing dir → no-op (`Ok(())`).
    /// - YAML entry with an existing `id` is **replaced** in-place.
    /// - YAML entry with a fresh `id` is **appended** to the
    ///   language's list (creating the language bucket if needed).
    /// - `<root>/.lain/patterns/<lang>/*.scm` are layered on top of
    ///   the bundled query map: each body is validated via
    ///   `tree_sitter::Query::new` up front. A malformed body fails
    ///   the whole call with
    ///   [`PatternsError::OverrideQuerySyntax`].
    pub fn load_overrides(&mut self, root: &Path) -> Result<(), PatternsError> {
        let dir = root.join(".lain").join("patterns");
        if !dir.exists() {
            self.overrides_applied = true;
            return Ok(());
        }

        // Step 1: validate every override `.scm` body BEFORE mutating
        // self. The collected bodies + key live in `pending_scml`
        // until we know every one of them parses against its grammar.
        let mut pending_scml: Vec<(String, String)> = Vec::new();
        for lang_dir in walk_lang_dirs(&dir)? {
            let read_dir = match std::fs::read_dir(&lang_dir) {
                Ok(d) => d,
                Err(e) => {
                    return Err(PatternsError::OverrideRead {
                        path: lang_dir.clone(),
                        source: e,
                    })
                }
            };
            for entry in read_dir.flatten() {
                let path = entry.path();
                if path.extension().and_then(|e| e.to_str()) != Some("scm") {
                    continue;
                }
                let stem = path
                    .file_name()
                    .and_then(|n| n.to_str())
                    .unwrap_or_else(|| panic!("invalid .scm path: {}", path.display()))
                    .to_string();
                let lang_yaml = lang_dir
                    .file_name()
                    .and_then(|n| n.to_str())
                    .unwrap_or("unknown")
                    .to_string();
                let key = format!("{lang_yaml}/{stem}");
                let body =
                    std::fs::read_to_string(&path).map_err(|e| PatternsError::OverrideRead {
                        path: path.clone(),
                        source: e,
                    })?;
                validate_scm_body(&key, &body)?;
                pending_scml.push((key, body));
            }
        }

        // Step 2: parse + apply. Validation here only catches YAML
        // structure errors; the `.scm` validation already ran above.
        let overrides = YamlFile::load_from_dir(&dir)?;
        for (lang, list) in overrides.languages {
            for new_def in list {
                if let Some(existing) = self.framework_mut(&new_def.id) {
                    *existing = new_def;
                } else {
                    self.yaml
                        .languages
                        .entry(lang.clone())
                        .or_default()
                        .push(new_def);
                }
            }
        }
        // Populate the override cache exactly once. Bodies were
        // validated above (Step 1); the OnceLock guards against
        // double-load — a second `load_overrides` on the same
        // `Patterns` instance is treated as a no-op with a warning,
        // matching the brief's "startup-only path" rationale.
        if self.override_scml.get().is_some() {
            eprintln!(
                "warning: Patterns::load_overrides called twice on the same instance — \
                   second call ignored; the per-instance cache was already populated from the first load"
            );
        } else {
            let _ = self.override_scml.set(pending_scml);
        }

        self.overrides_applied = true;
        Ok(())
    }

    /// `true` once [`Self::load_overrides`] has run, regardless of
    /// whether it merged anything. Useful for diagnostics.
    pub fn overrides_applied(&self) -> bool {
        self.overrides_applied
    }
}

/// What failed during a Patterns operation. The brief requires a
/// *structured* error for malformed YAML — `serde_yaml::Error` carries
/// line / column info.
#[derive(Debug, thiserror::Error)]
pub enum PatternsError {
    #[error("malformed frameworks YAML: {0}")]
    Yaml(#[from] serde_yaml::Error),
    #[error("could not read override directory {path:?}: {source}")]
    OverrideRead {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("invalid tree-sitter query in override .scm file {path:?}: {message} (row {row}, column {column})")]
    OverrideQuerySyntax {
        path: String,
        row: usize,
        column: usize,
        message: String,
    },
}

/// Validate a `.scm` body against the grammar registered for its
/// `<lang>/` bucket prefix. Bundled bodies go through the same
/// `tree_sitter::Query::new` call in `patterns/build.rs` at build
/// time, so this is the runtime second leg for override bodies.
///
/// `key` is the `<lang>/<framework>.scm` form (or any labelled
/// string the caller wants surfaced on error). The grammar lookup
/// mirrors `src/server/sensors/util.rs::grammar_for` so a runtime
/// panic and a build-time panic name the same grammar.
fn validate_scm_body(key: &str, body: &str) -> Result<(), PatternsError> {
    let (lang_yaml, _) = key
        .split_once('/')
        .ok_or_else(|| PatternsError::OverrideQuerySyntax {
            path: key.to_string(),
            row: 0,
            column: 0,
            message: "expected key of the form '<lang>/<framework>.scm'".to_string(),
        })?;
    let grammar =
        grammar_for_yaml_key(lang_yaml).ok_or_else(|| PatternsError::OverrideQuerySyntax {
            path: key.to_string(),
            row: 0,
            column: 0,
            message: format!("no tree-sitter grammar registered for lang bucket {lang_yaml:?}"),
        })?;
    tree_sitter::Query::new(&grammar, body)
        .map(|_| ())
        .map_err(|e| PatternsError::OverrideQuerySyntax {
            path: key.to_string(),
            row: e.row,
            column: e.column,
            message: format!("{}: {}", query_error_kind_str(&e.kind), e.message),
        })
}

/// Resolve a tree-sitter [`tree_sitter::Language`] for the language
/// bucket key (`rust`, `python`, `tsjs`, …). Mirrors
/// `src/server/sensors/util.rs::grammar_for` so a runtime panic
/// names the same grammar as the build-time validator.
fn grammar_for_yaml_key(lang_yaml: &str) -> Option<tree_sitter::Language> {
    use crate::server::sensors::util::language_for;
    let lang = match lang_yaml {
        "rust" => Some(Lang::Rust),
        "python" => Some(Lang::Python),
        "tsjs" => Some(Lang::TsJs),
        "go" => Some(Lang::Go),
        "java" => Some(Lang::Java),
        "csharp" => Some(Lang::CSharp),
        "ruby" => Some(Lang::Ruby),
        "kotlin" => Some(Lang::Kotlin),
        // `ts` / `tsx` directories are not currently emitted by the
        // override walker (the bundled patterns split TypeScript and
        // JavaScript under a single `tsjs/` bucket) but the route is
        // reserved for a future expansion.
        "ts" => Some(Lang::Ts),
        "tsx" => Some(Lang::Tsx),
        _ => None,
    }?;
    Some(language_for(lang))
}

/// Walk `<root>/<lang>/` directories and return them. Mirrors
/// `patterns/build.rs::discover_lang_dirs` for the runtime override
/// path so an org's `<root>/.lain/patterns/rust/axum-route.scm`
/// shadows the bundled `axum-route.scm`.
fn walk_lang_dirs(root: &Path) -> Result<Vec<PathBuf>, PatternsError> {
    let read_dir = std::fs::read_dir(root).map_err(|e| PatternsError::OverrideRead {
        path: root.to_path_buf(),
        source: e,
    })?;
    let mut langs: Vec<PathBuf> = read_dir
        .filter_map(Result::ok)
        .filter(|e| e.path().is_dir())
        .filter(|e| !e.file_name().to_string_lossy().starts_with('.'))
        .map(|e| e.path())
        .collect();
    langs.sort();
    Ok(langs)
}

/// Render a [`tree_sitter::QueryErrorKind`] as a stable human label
/// so the structured error surfaces the failure class (`Syntax`,
/// `NodeType`, …). Mirrors the labels `tree-sitter`'s own `Display`
/// uses; we spell them out explicitly rather than depending on tree-
/// sitter's Display implementation which couples to the source preview
/// layout.
fn query_error_kind_str(kind: &tree_sitter::QueryErrorKind) -> &'static str {
    use tree_sitter::QueryErrorKind;
    match kind {
        QueryErrorKind::Syntax => "Invalid syntax",
        QueryErrorKind::NodeType => "Invalid node type",
        QueryErrorKind::Field => "Invalid field name",
        QueryErrorKind::Capture => "Invalid capture name",
        QueryErrorKind::Predicate => "Invalid predicate",
        QueryErrorKind::Structure => "Impossible pattern",
        QueryErrorKind::Language => "Language mismatch",
    }
}

/// Map a [`Lang`] to the YAML bucket key. `Ts` and `Tsx` share the
/// `tsjs` bucket because the existing `http_sensor` /
/// `http_client_sensor` walkers treat them uniformly.
fn lang_key(lang: Lang) -> &'static str {
    match lang {
        Lang::Python => "python",
        Lang::TsJs | Lang::Ts | Lang::Tsx => "tsjs",
        Lang::Rust => "rust",
        Lang::Go => "go",
        Lang::Java => "java",
        Lang::CSharp => "csharp",
        Lang::Ruby => "ruby",
        Lang::Kotlin => "kotlin",
    }
}

/// Match `lib` against `pattern` as a regex. Compiled on every call —
/// `lib_match` is small (5-10 chars per definition) and `deny_methods_for`
/// is on the cold path; a `OnceLock<Regex>` cache would be premature
/// optimisation.
fn regex_match(pattern: &str, lib: &str) -> bool {
    match regex::Regex::new(pattern) {
        Ok(re) => re.is_match(lib),
        // A malformed regex would be a load-time bug, not a runtime
        // one. The bundled YAML is exercised by tests, so a malformed
        // entry surfaces immediately.
        Err(_) => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lang_key_handles_every_variant() {
        // Pin the mapping — `lang_key` is the contract between the
        // YAML keys and the `Lang` enum. Drift here is silent
        // (returns an empty iterator) but breaks every sensor.
        assert_eq!(lang_key(Lang::Python), "python");
        assert_eq!(lang_key(Lang::TsJs), "tsjs");
        assert_eq!(lang_key(Lang::Ts), "tsjs");
        assert_eq!(lang_key(Lang::Tsx), "tsjs");
        assert_eq!(lang_key(Lang::Rust), "rust");
        assert_eq!(lang_key(Lang::Go), "go");
        assert_eq!(lang_key(Lang::Java), "java");
        assert_eq!(lang_key(Lang::CSharp), "csharp");
        assert_eq!(lang_key(Lang::Ruby), "ruby");
        assert_eq!(lang_key(Lang::Kotlin), "kotlin");
    }
}
