//! Data-driven pattern loader (`§6.1` of the data-driven sensor
//! patterns plan).
//!
//! Camp-A patterns (regex / text / `deny_methods`) come from
//! [`frameworks.yaml`]. Camp-B patterns (Tree-sitter structural queries)
// live as `<lang>/<framework>.scm` files compiled by `patterns/build.rs`
// into a static map exposed via [`generated::queries`]. The sensor
//! walkers consume both via [`Patterns`].
//!
//! ## Lifecycle
//!
//! [`Patterns::patterns`] returns a `&'static Patterns` initialised
//! once via [`OnceLock`] from the bundled YAML. After the per-sensor
//! walkers consume it (Tasks 2-4), [`Patterns::load_overrides`] layers
//! `<repo>/.lain/patterns/*.{yaml,scm}` on top so an org can extend or
//! replace a bundled pattern without rebuilding LAIN.

use crate::server::sensors::util::Lang;
use serde::Deserialize;
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

/// Generated by `patterns/build.rs`. The actual contents live in
/// `$OUT_DIR/queries.rs`; this re-export is how the build pipeline
/// makes the file visible without committing generated output to
/// version control.
pub mod generated {
    include!(env!("LAIN_PATTERNS_GENERATED_QUERIES"));
}

/// One entry in [`YamlFile`]. A `kind` discriminator (`route`,
/// `outbound`, or `entrypoint`) decides which iterator on [`Patterns`]
/// yields it.
///
/// All fields default to empty / `None` so an entry only spells out the
/// attributes the framework actually exposes.
#[derive(Debug, Deserialize, Clone, PartialEq, Eq)]
pub struct FrameworkDef {
    /// Stable, file-unique identifier (`fastapi-route`,
    /// `reqwest-outbound`, …). Overrides match by `id`.
    pub id: String,
    pub kind: FrameworkKind,
    /// Verbs the framework's call shape can take. Lower-case strings
    /// (`get`, `post`, …). Empty for outbound definitions where the
    /// verb is a kwarg or first-arg kind.
    #[serde(default)]
    pub verbs: Vec<String>,
    /// Regex matched against the receiver text (`requests.<verb>` →
    /// `requests`). `None` means "match anything" — used by entry
    /// points that have no library prefix.
    #[serde(default)]
    pub lib_match: Option<String>,
    /// Methods the receiver-shape walker should ignore when reading
    /// a bound response (body parsers and response metadata).
    #[serde(default)]
    pub deny_methods: Vec<String>,
    /// Framework-specific source-file name (e.g. Rails's
    /// `config/routes.rb`). When `Some(_)`, only files matching this
    /// are scanned for the pattern.
    #[serde(default)]
    pub source: Option<String>,
    /// Regex path-shape fallback for frameworks where the structural
    /// query is not yet populated.
    #[serde(default)]
    pub path_regex: Option<String>,
    /// Regex handler-shape fallback.
    #[serde(default)]
    pub handler_regex: Option<String>,
    /// Framework annotation name (Spring `@GetMapping`,
    /// ASP.NET `[HttpGet]`).
    #[serde(default)]
    pub annotation: Option<String>,
}

/// What role this framework plays in the federation graph.
#[derive(Debug, Deserialize, Clone, Copy, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum FrameworkKind {
    /// Inbound route: emits `HttpRoute` + `CallsHttp` (`http_sensor`).
    Route,
    /// Outbound call: emits `HttpClientCall` (`http_client_sensor`).
    Outbound,
    /// Entry point: HTTP handlers, scheduled jobs, CLI commands,
    /// `fn main` (`entry_point_sensor`).
    EntryPoint,
}

/// Top-level YAML document.
///
/// ```text
/// languages:
///   <lang-key>:
///     - id: <stable-id>
///       kind: <route|outbound|entrypoint>
///       verbs: [...]
///       lib_match: "<regex>"
///       deny_methods: [...]
///       source: "<relative path>"
///       path_regex: "<regex>"
///       handler_regex: "<regex>"
///       annotation: "<regex>"
/// ```
#[derive(Debug, Deserialize, Clone, Default)]
pub struct YamlFile {
    pub languages: BTreeMap<String, Vec<FrameworkDef>>,
}

impl YamlFile {
    /// Load every `*.yaml` in `dir` and concatenate the entries.
    /// Bundled YAML and runtime overrides use the same schema; the
    /// override path uses this to merge per-repo additions.
    pub fn load_from_dir(dir: &Path) -> Result<Self, PatternsError> {
        let mut out = YamlFile::default();
        let entries = std::fs::read_dir(dir).map_err(|e| PatternsError::OverrideRead {
            path: dir.to_path_buf(),
            source: e,
        })?;
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) != Some("yaml") {
                continue;
            }
            let text = std::fs::read_to_string(&path).map_err(|e| PatternsError::OverrideRead {
                path: path.clone(),
                source: e,
            })?;
            let doc: YamlFile = serde_yaml::from_str(&text)?;
            for (lang, list) in doc.languages {
                out.languages.entry(lang).or_default().extend(list);
            }
        }
        Ok(out)
    }
}

/// The pattern registry. One instance per process, loaded once via
/// [`Patterns::patterns`]. Per-repo overrides are layered on top via
/// [`Patterns::load_overrides`].
///
/// All accessors return `&FrameworkDef` borrowed from `&'static` data
/// (the bundled YAML is `include_str!`'d), so the registry is safe to
/// share across threads without locking.
#[derive(Debug, Clone)]
pub struct Patterns {
    yaml: YamlFile,
    overrides_applied: bool,
}

impl Patterns {
    /// Parse `s` as a YAML document. Returns the structured
    /// `serde_yaml::Error` on failure so callers (tests, ops) get
    /// the line / column of the offending entry.
    pub fn from_yaml_str(s: &str) -> Result<Self, PatternsError> {
        let yaml: YamlFile = serde_yaml::from_str(s)?;
        Ok(Self {
            yaml,
            overrides_applied: false,
        })
    }

    /// Parse a YAML file from disk.
    pub fn from_yaml_file(path: &Path) -> Result<Self, PatternsError> {
        let text = std::fs::read_to_string(path).map_err(|e| PatternsError::OverrideRead {
            path: path.to_path_buf(),
            source: e,
        })?;
        Self::from_yaml_str(&text)
    }

    /// Return the bundled singleton. First call parses
    /// `frameworks.yaml`; every later call shares the same instance
    /// (the underlying YAML is `include_str!`'d so the parsed data
    /// lives in static storage).
    #[allow(clippy::self_named_constructors)]
    pub fn patterns() -> &'static Self {
        static DEFAULT: OnceLock<Patterns> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            Self::from_yaml_str(include_str!("frameworks.yaml"))
                .expect("bundled frameworks.yaml must parse")
        })
    }

    /// Deprecated alias for [`Patterns::patterns`]. Kept so existing
    /// callers (and the prior task's tests) keep compiling while the
    /// canonical name lands.
    #[deprecated(note = "use Patterns::patterns() instead")]
    pub fn load_default() -> &'static Self {
        Self::patterns()
    }

    /// Return every compiled (Camp-B) `.scm` query bundled into the
    /// binary. Each entry is `(key, lang, framework, body)` where
    /// `key = "<lang>/<framework>.scm"`. The slice is sorted by key
    /// so a binary search (`generated::get`) is `O(log n)`.
    ///
    /// Tasks 2-4 iterate this slice and parse each body via
    /// `tree_sitter::Query::new`.
    pub fn compiled_queries(
        &self,
    ) -> &'static [(&'static str, &'static str, &'static str, &'static str)] {
        generated::QUERIES
    }

    /// Clone the bundled singleton into an owned [`Patterns`] so
    /// callers can layer overrides without touching the global
    /// default. `load_overrides` mutates the cloned value.
    pub fn clone_default() -> Self {
        Self::patterns().clone()
    }

    /// Look up a framework by `id` across every language.
    pub fn framework(&self, id: &str) -> Option<&FrameworkDef> {
        self.yaml
            .languages
            .values()
            .flat_map(|v| v.iter())
            .find(|f| f.id == id)
    }

    /// Mutable version of [`Self::framework`].
    fn framework_mut(&mut self, id: &str) -> Option<&mut FrameworkDef> {
        self.yaml
            .languages
            .values_mut()
            .flat_map(|v| v.iter_mut())
            .find(|f| f.id == id)
    }

    /// Iterate route frameworks for `lang` in the order the YAML
    /// listed them. `Lang::Ts` and `Lang::Tsx` share the `tsjs`
    /// bucket — the existing `http_sensor` regex does not
    /// distinguish them either.
    pub fn route_patterns(&self, lang: Lang) -> impl Iterator<Item = &FrameworkDef> {
        let key = lang_key(lang);
        self.yaml
            .languages
            .get(key)
            .into_iter()
            .flatten()
            .filter(|f| f.kind == FrameworkKind::Route)
    }

    /// Iterate outbound-call frameworks for `lang`.
    pub fn outbound_patterns(&self, lang: Lang) -> impl Iterator<Item = &FrameworkDef> {
        let key = lang_key(lang);
        self.yaml
            .languages
            .get(key)
            .into_iter()
            .flatten()
            .filter(|f| f.kind == FrameworkKind::Outbound)
    }

    /// Iterate entry-point frameworks for `lang`.
    pub fn entry_point_patterns(&self, lang: Lang) -> impl Iterator<Item = &FrameworkDef> {
        let key = lang_key(lang);
        self.yaml
            .languages
            .get(key)
            .into_iter()
            .flatten()
            .filter(|f| f.kind == FrameworkKind::EntryPoint)
    }

    /// Return the union of `deny_methods` across every outbound
    /// definition whose `lib_match` regex accepts `lib`.
    ///
    /// `_verb` is reserved for forward compatibility — Tasks 2-4 may
    /// narrow the deny surface by verb (e.g. only deny `requests.get`
    /// but not `requests.post`). Today the parameter is unused.
    ///
    /// No regex match (`lib_match` is `None`) means "any library
    /// matches"; this preserves the framework's deny surface even
    /// when the framework doesn't pin a specific library name.
    pub fn deny_methods_for(&self, lang: Lang, lib: &str, _verb: &str) -> Vec<String> {
        let key = lang_key(lang);
        let mut out = Vec::new();
        if let Some(list) = self.yaml.languages.get(key) {
            for def in list {
                if def.kind != FrameworkKind::Outbound {
                    continue;
                }
                let accepts = match def.lib_match.as_deref() {
                    None => true,
                    Some(re) => regex_match(re, lib),
                };
                if accepts {
                    out.extend(def.deny_methods.iter().cloned());
                }
            }
        }
        // Deduplicate while preserving first-seen order so callers
        // can compare against a stable list.
        let mut seen = std::collections::HashSet::new();
        out.retain(|m| seen.insert(m.clone()));
        out
    }

    /// Layer per-repo overrides from `<root>/.lain/patterns/`.
    ///
    /// - Missing dir → no-op (`Ok(())`).
    /// - Entry with an existing `id` is **replaced** in-place.
    /// - Entry with a fresh `id` is **appended** to the language's
    ///   list (creating the language bucket if needed).
    pub fn load_overrides(&mut self, root: &Path) -> Result<(), PatternsError> {
        let dir = root.join(".lain").join("patterns");
        if !dir.exists() {
            self.overrides_applied = true;
            return Ok(());
        }
        let overrides = YamlFile::load_from_dir(&dir)?;
        for (lang, list) in overrides.languages {
            for new_def in list {
                if let Some(existing) = self.framework_mut(&new_def.id) {
                    *existing = new_def;
                } else {
                    self.yaml
                        .languages
                        .entry(lang.clone())
                        .or_default()
                        .push(new_def);
                }
            }
        }
        self.overrides_applied = true;
        Ok(())
    }

    /// `true` once [`Self::load_overrides`] has run, regardless of
    /// whether it merged anything. Useful for diagnostics.
    pub fn overrides_applied(&self) -> bool {
        self.overrides_applied
    }
}

/// What failed during a Patterns operation. The brief requires a
/// *structured* error for malformed YAML — `serde_yaml::Error` carries
/// line / column info.
#[derive(Debug, thiserror::Error)]
pub enum PatternsError {
    #[error("malformed frameworks YAML: {0}")]
    Yaml(#[from] serde_yaml::Error),
    #[error("could not read override directory {path:?}: {source}")]
    OverrideRead {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
}

/// Map a [`Lang`] to the YAML bucket key. `Ts` and `Tsx` share the
/// `tsjs` bucket because the existing `http_sensor` /
/// `http_client_sensor` walkers treat them uniformly.
fn lang_key(lang: Lang) -> &'static str {
    match lang {
        Lang::Python => "python",
        Lang::TsJs | Lang::Ts | Lang::Tsx => "tsjs",
        Lang::Rust => "rust",
        Lang::Go => "go",
        Lang::Java => "java",
        Lang::CSharp => "csharp",
        Lang::Ruby => "ruby",
        Lang::Kotlin => "kotlin",
    }
}

/// Match `lib` against `pattern` as a regex. Compiled on every call —
/// `lib_match` is small (5-10 chars per definition) and `deny_methods_for`
/// is on the cold path; a `OnceLock<Regex>` cache would be premature
/// optimisation.
fn regex_match(pattern: &str, lib: &str) -> bool {
    match regex::Regex::new(pattern) {
        Ok(re) => re.is_match(lib),
        // A malformed regex would be a load-time bug, not a runtime
        // one. The bundled YAML is exercised by tests, so a malformed
        // entry surfaces immediately.
        Err(_) => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lang_key_handles_every_variant() {
        // Pin the mapping — `lang_key` is the contract between the
        // YAML keys and the `Lang` enum. Drift here is silent
        // (returns an empty iterator) but breaks every sensor.
        assert_eq!(lang_key(Lang::Python), "python");
        assert_eq!(lang_key(Lang::TsJs), "tsjs");
        assert_eq!(lang_key(Lang::Ts), "tsjs");
        assert_eq!(lang_key(Lang::Tsx), "tsjs");
        assert_eq!(lang_key(Lang::Rust), "rust");
        assert_eq!(lang_key(Lang::Go), "go");
        assert_eq!(lang_key(Lang::Java), "java");
        assert_eq!(lang_key(Lang::CSharp), "csharp");
        assert_eq!(lang_key(Lang::Ruby), "ruby");
        assert_eq!(lang_key(Lang::Kotlin), "kotlin");
    }
}
