//! Data-driven pattern loader (`§6.1` of the data-driven sensor
//! patterns plan).
//!
//! Camp-A patterns (regex / text / `deny_methods`) come from
//! [`frameworks.yaml`]. Camp-B patterns (Tree-sitter structural queries)
// live as `<lang>/<framework>.scm` files compiled by `patterns/build.rs`
// into a static map exposed via [`generated::queries`]. The sensor
//! walkers consume both via [`Patterns`].
//!
//! ## Lifecycle
//!
//! [`Patterns::patterns`] returns a `&'static Patterns` initialised
//! once via [`OnceLock`] from the bundled YAML. After the per-sensor
//! walkers consume it (Tasks 2-4), [`Patterns::load_overrides`] layers
//! `<repo>/.lain/patterns/*.{yaml,scm}` on top so an org can extend or
//! replace a bundled pattern without rebuilding LAIN.

use crate::federation::contracts::model::HttpMethod;
use crate::server::sensors::util::Lang;
use serde::Deserialize;
use std::borrow::Cow;
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

/// Generated by `patterns/build.rs`. The actual contents live in
/// `$OUT_DIR/queries.rs`; this re-export is how the build pipeline
/// makes the file visible without committing generated output to
/// version control.
pub mod generated {
    include!(env!("LAIN_PATTERNS_GENERATED_QUERIES"));
}

/// One entry in [`YamlFile`]. A `kind` discriminator (`route`,
/// `outbound`, or `entrypoint`) decides which iterator on [`Patterns`]
/// yields it.
///
/// All fields default to empty / `None` so an entry only spells out the
/// attributes the framework actually exposes.
#[derive(Debug, Deserialize, Clone, PartialEq, Eq)]
pub struct FrameworkDef {
    /// Stable, file-unique identifier (`fastapi-route`,
    /// `reqwest-outbound`, …). Overrides match by `id`.
    pub id: String,
    /// Optional "what the walker calls this framework" — for
    /// frameworks whose YAML identifier is a different spelling
    /// than the lib's actual import (`Net::HTTP` for
    /// `net-http-outbound`, `HttpClient` for `httpclient-outbound`,
    /// …). When `Some(_)`, the walker uses `display_name` instead
    /// of `id` for `is_known_library`, `via_lib`, and verb
    /// normalisation lookups so the per-framework hardcoded match
    /// arms disappear from `http_client_sensor.rs`. `None` (the
    /// default) means "use `id`" — no change to existing entries.
    ///
    /// The intent is to let a future framework declare its
    /// `display_name` in YAML and remove the corresponding
    /// hardcoded match arm in the walker. Adding
    /// `display_name` to entries that don't currently have a
    /// hardcoded mapping is **not** what this field is for —
    /// keep the YAML minimal.
    #[serde(default)]
    pub display_name: Option<String>,
    pub kind: FrameworkKind,
    /// Verbs the framework's call shape can take. Lower-case strings
    /// (`get`, `post`, …). Empty for outbound definitions where the
    /// verb is a kwarg or first-arg kind.
    #[serde(default)]
    pub verbs: Vec<String>,
    /// Regex matched against the receiver text (`requests.<verb>` →
    /// `requests`). `None` means "match anything" — used by entry
    /// points that have no library prefix.
    #[serde(default)]
    pub lib_match: Option<String>,
    /// Methods the receiver-shape walker should ignore when reading
    /// a bound response (body parsers and response metadata).
    #[serde(default)]
    pub deny_methods: Vec<String>,
    /// Framework-specific source-file name (e.g. Rails's
    /// `config/routes.rb`). When `Some(_)`, only files matching this
    /// are scanned for the pattern.
    #[serde(default)]
    pub source: Option<String>,
    /// Regex path-shape fallback for frameworks where the structural
    /// query is not yet populated.
    #[serde(default)]
    pub path_regex: Option<String>,
    /// Regex handler-shape fallback.
    #[serde(default)]
    pub handler_regex: Option<String>,
    /// Framework annotation name (Spring `@GetMapping`,
    /// ASP.NET `[HttpGet]`).
    #[serde(default)]
    pub annotation: Option<String>,
}

impl FrameworkDef {
    /// The identifier the walker should use for "is this framework
    /// the X?" lookups. Defaults to [`Self::id`]; returns
    /// [`Self::display_name`] when set. A regression that drops
    /// this helper (and inlines `framework.id` back into the walker)
    /// re-introduces the per-framework hardcoded match arms — keep
    /// this single funnel the canonical source.
    pub fn effective_id(&self) -> &str {
        self.display_name.as_deref().unwrap_or(self.id.as_str())
    }
}

/// What role this framework plays in the federation graph.
#[derive(Debug, Deserialize, Clone, Copy, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum FrameworkKind {
    /// Inbound route: emits `HttpRoute` + `CallsHttp` (`http_sensor`).
    Route,
    /// Outbound call: emits `HttpClientCall` (`http_client_sensor`).
    Outbound,
    /// Entry point: HTTP handlers, scheduled jobs, CLI commands,
    /// `fn main` (`entry_point_sensor`).
    EntryPoint,
}

/// Top-level YAML document.
///
/// ```text
/// languages:
///   <lang-key>:
///     - id: <stable-id>
///       kind: <route|outbound|entrypoint>
///       verbs: [...]
///       lib_match: "<regex>"
///       deny_methods: [...]
///       source: "<relative path>"
///       path_regex: "<regex>"
///       handler_regex: "<regex>"
///       annotation: "<regex>"
/// ```
#[derive(Debug, Deserialize, Clone, Default)]
pub struct YamlFile {
    pub languages: BTreeMap<String, Vec<FrameworkDef>>,
}

impl YamlFile {
    /// Load every `*.yaml` in `dir` and concatenate the entries.
    /// Bundled YAML and runtime overrides use the same schema; the
    /// override path uses this to merge per-repo additions.
    pub fn load_from_dir(dir: &Path) -> Result<Self, PatternsError> {
        let mut out = YamlFile::default();
        let entries = std::fs::read_dir(dir).map_err(|e| PatternsError::OverrideRead {
            path: dir.to_path_buf(),
            source: e,
        })?;
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) != Some("yaml") {
                continue;
            }
            let text = std::fs::read_to_string(&path).map_err(|e| PatternsError::OverrideRead {
                path: path.clone(),
                source: e,
            })?;
            let doc: YamlFile = serde_yaml::from_str(&text)?;
            for (lang, list) in doc.languages {
                out.languages.entry(lang).or_default().extend(list);
            }
        }
        Ok(out)
    }
}

/// The pattern registry. One instance per process, loaded once via
/// [`Patterns::patterns`]. Per-repo overrides are layered on top via
/// [`Patterns::load_overrides`].
///
/// All accessors return `&FrameworkDef` borrowed from `&'static` data
/// (the bundled YAML is `include_str!`'d), so the registry is safe to
/// share across threads without locking.
///
/// `override_scml` is the per-instance cache of override `.scm` bodies
/// loaded from `<root>/.lain/patterns/<lang>/*.scm` by
/// [`Self::load_overrides`]. Each body is keyed by
/// `<lang>/<framework>.scm` and validated via
/// `tree_sitter::Query::new` at load time — a syntax error fails
/// `load_overrides` with a structured `PatternsError::OverrideQuerySyntax`
/// and never reaches the compiled-queries surface.
///
/// The cache is a plain `Vec<(String, String)>` rather than a
/// `OnceLock<Vec<…>>` (the parked-2 cleanup pass's choice): a second
/// `load_overrides` call legitimately re-loads (the all-or-nothing
/// semantic is the wholesale replace — old bodies are dropped, new
/// bodies take their place — not the "second call is a no-op" of the
/// previous design). The walker code is single-threaded per scan, so
/// the cache mutation is contained to the calling scan; concurrent
/// scans from different threads each hold their own `Patterns` clone.
/// Cloning the registry snapshots the current bodies into a fresh
/// `Vec`; a clone that runs `load_overrides` does not perturb the
/// original's cache.
pub struct Patterns {
    yaml: YamlFile,
    overrides_applied: bool,
    /// Override `.scm` bodies loaded from `<root>/.lain/patterns/<lang>/`.
    /// Each entry is `(key, body)` where `key = "<lang>/<framework>.scm"`.
    /// Validation happened when the entry was inserted; the cache only
    /// stores bodies that already passed `tree_sitter::Query::new`.
    /// Replaced wholesale by [`Self::load_overrides`] on every call —
    /// see the field-level doc-comment for the all-or-nothing
    /// rationale.
    override_scml: Vec<(String, String)>,
    /// Cache of the merged query map (`bundled + override` bodies,
    /// with overrides replacing bundled entries on key conflict and
    /// appending for fresh keys). Stores OWNED strings so the
    /// `compiled_queries` accessor can return a slice with `&'a str`
    /// elements borrowing from `&self` (no `Box::leak` needed).
    /// Populated lazily on the first `compiled_queries()` call that
    /// finds non-empty overrides; invalidated on every successful
    /// `load_overrides` so the next call rebuilds with the new
    /// override bodies.
    merged_queries: OnceLock<Vec<(String, String, String, String)>>,
    /// Cache of the compiled route-pattern `BTreeMap` keyed by
    /// `<lang>-<framework>`. The map is built once per `Patterns`
    /// instance and reused by every `get_route_patterns` /
    /// `route_patterns_map` call. Storing the cache on the
    /// `Patterns` instance (rather than a per-pointer
    /// `thread_local!` keyed on the patterns' raw address) closes
    /// the leak-across-scans bug where two consecutive scans
    /// happened to allocate their `Patterns` clones at the same
    /// address and the second scan inherited the first scan's
    /// override-augmented route map. Invalidation on
    /// `load_overrides` is required because override `.yaml` files
    /// can replace or append framework entries the route-patterns
    /// builder consumes (`route_patterns(Lang)`).
    route_patterns_cache: OnceLock<BTreeMap<String, RoutePattern>>,
}

impl std::fmt::Debug for Patterns {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Patterns")
            .field(
                "yaml_languages",
                &self.yaml.languages.keys().collect::<Vec<_>>(),
            )
            .field("overrides_applied", &self.overrides_applied)
            .field("override_scml_count", &self.override_scml.len())
            .field(
                "merged_queries_populated",
                &self.merged_queries.get().is_some(),
            )
            .field(
                "route_patterns_cache_populated",
                &self.route_patterns_cache.get().is_some(),
            )
            .finish()
    }
}

impl Clone for Patterns {
    fn clone(&self) -> Self {
        // Snapshot the current override bodies into a fresh `Vec`.
        // The clone is independent: a subsequent `load_overrides` on
        // the clone mutates only the clone's cache. This matches the
        // `Mutex<Vec<...>>::clone()` semantics the parked-2 cleanup
        // pass replaced — each clone has its own backing store.
        //
        // The merged-queries cache is carried over too — if the
        // source has already populated it, the clone reuses the
        // same owned data so the merge work doesn't repeat. The
        // returned slice from `compiled_queries()` borrows from
        // `&self`, so the clone's lifetime ties the slice to the
        // clone. When the source's cache is empty, the clone starts
        // fresh — `compiled_queries()` will rebuild on its first
        // call.
        let merged_queries: OnceLock<Vec<(String, String, String, String)>> =
            match self.merged_queries.get() {
                Some(v) => {
                    let once = OnceLock::new();
                    // `set` cannot fail here — the OnceLock was just
                    // constructed, no other thread can have populated
                    // it.
                    let _ = once.set(v.clone());
                    once
                }
                None => OnceLock::new(),
            };
        // `RoutePattern` doesn't implement `Clone` (it owns a
        // `regex::Regex`), so the route-patterns cache cannot be
        // carried over to the clone. The clone starts with an
        // empty `OnceLock` and `route_patterns_map()` rebuilds
        // via `get_or_init` on first call — one rebuild per clone,
        // which preserves the wire-in-2 invariant that the cache
        // lives on the instance, not the process.
        let route_patterns_cache: OnceLock<BTreeMap<String, RoutePattern>> = OnceLock::new();
        Self {
            yaml: self.yaml.clone(),
            overrides_applied: self.overrides_applied,
            override_scml: self.override_scml.clone(),
            merged_queries,
            route_patterns_cache,
        }
    }
}

impl Patterns {
    /// Parse `s` as a YAML document. Returns the structured
    /// `serde_yaml::Error` on failure so callers (tests, ops) get
    /// the line / column of the offending entry.
    pub fn from_yaml_str(s: &str) -> Result<Self, PatternsError> {
        let yaml: YamlFile = serde_yaml::from_str(s)?;
        Ok(Self {
            yaml,
            overrides_applied: false,
            override_scml: Vec::new(),
            merged_queries: OnceLock::new(),
            route_patterns_cache: OnceLock::new(),
        })
    }

    /// Parse a YAML file from disk.
    pub fn from_yaml_file(path: &Path) -> Result<Self, PatternsError> {
        let text = std::fs::read_to_string(path).map_err(|e| PatternsError::OverrideRead {
            path: path.to_path_buf(),
            source: e,
        })?;
        Self::from_yaml_str(&text)
    }

    /// Return the bundled singleton. First call parses
    /// `frameworks.yaml`; every later call shares the same instance
    /// (the underlying YAML is `include_str!`'d so the parsed data
    /// lives in static storage).
    #[allow(clippy::self_named_constructors)]
    pub fn patterns() -> &'static Self {
        static DEFAULT: OnceLock<Patterns> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            Self::from_yaml_str(include_str!("frameworks.yaml"))
                .expect("bundled frameworks.yaml must parse")
        })
    }

    /// Deprecated alias for [`Patterns::patterns`]. Kept so existing
    /// callers (and the prior task's tests) keep compiling while the
    /// canonical name lands.
    #[deprecated(note = "use Patterns::patterns() instead")]
    pub fn load_default() -> &'static Self {
        Self::patterns()
    }

    /// Return every compiled (Camp-B) `.scm` query bundled into the
    /// binary, plus any runtime-loaded override bodies.
    ///
    /// Each tuple is `(key, lang, framework, body)` where
    /// `key = "<lang>/<framework>.scm"`. The slice is sorted by key
    /// so a binary search (`generated::get`) is `O(log n)`.
    ///
    /// The bundled bodies are validated at build time by
    /// `patterns/build.rs` so a syntax error there fails `cargo build`
    /// rather than reaching this method. Override bodies loaded by
    /// [`Self::load_overrides`] are validated against their grammar
    /// **before** they land in the cache — once inserted, the cache
    /// is self-consistent and this method does not re-validate.
    ///
    /// When no overrides are loaded (the common case), the returned
    /// slice is a `Cow::Borrowed` of the bundled static — zero cost.
    /// When overrides are present, the method returns a `Cow::Owned`
    /// slice whose elements are `&'a str` slices borrowed from
    /// `&self.override_scml` (overrides) and `generated::QUERIES`
    /// (bundled). No `Box::leak` is involved: the cache stores
    /// owned `String`s and the slice borrows from them, with its
    /// lifetime tied to `&self`. A small per-call `Vec::with_capacity`
    /// + borrow-copy is the only allocation the override path
    /// performs.
    ///
    /// The cached merged data (`merged_queries: OnceLock<Vec<(String, String, String, String)>>`)
    /// is invalidated on every successful `load_overrides` (a fresh
    /// `OnceLock` is installed) so the next call rebuilds from the
    /// new override bodies. Cloning a `Patterns` after the cache is
    /// populated snapshots the populated `Vec` into the clone (the
    /// `Clone` impl), so the clone's first call doesn't re-run the
    /// merge.
    ///
    /// The returned `Cow` borrows from `&self`, so its lifetime is
    /// tied to the `Patterns` instance (not `'static`). The three
    /// production callers (`http_sensor`, `http_client_sensor`,
    /// `entry_point_sensor`) all consume the slice within the
    /// calling function's scope — no caller stores the returned
    /// reference in a `'static` slot — so the tightened lifetime is
    /// invisible at the call site.
    ///
    /// On success returns the merged map. The `Result` is kept for
    /// API compatibility — bodies are validated at `load_overrides`
    /// time, so the `Err` arm is unreachable; callers continue to
    /// match on `Result`.
    #[allow(clippy::type_complexity)]
    pub fn compiled_queries<'a>(
        &'a self,
    ) -> Result<Cow<'a, [(&'a str, &'a str, &'a str, &'a str)]>, PatternsError> {
        // Fast path — the common case where no overrides are loaded.
        // Return the bundled static directly with no allocation and
        // no leaks.
        if self.override_scml.is_empty() {
            return Ok(Cow::Borrowed(generated::QUERIES));
        }

        // Populate the cache on the first call that finds non-empty
        // overrides. The cache stores OWNED strings so the returned
        // slice can borrow `&'a str` from `&self` without `Box::leak`.
        // Re-entered on a second call: the OnceLock is already
        // populated, so the closure is skipped.
        if self.merged_queries.get().is_none() {
            let bundled = generated::QUERIES;
            let mut merged: Vec<(String, String, String, String)> =
                Vec::with_capacity(bundled.len() + self.override_scml.len());

            // `override_scml` is sorted by key (see
            // `load_overrides`), so the merge loop's "advance past
            // sorted overrides" logic is correct.
            let mut override_iter = self.override_scml.iter();
            let mut next_override: Option<&(String, String)> = override_iter.next();
            for entry in bundled {
                let (key, lang, framework, body) = *entry;
                // Advance through any overrides whose key sorts
                // before the current bundled key (those are
                // appends).
                while let Some(ov) = next_override {
                    if ov.0.as_str() < key {
                        let (lang_part, framework_part) =
                            ov.0.split_once('/').unwrap_or((ov.0.as_str(), ""));
                        merged.push((
                            ov.0.clone(),
                            lang_part.to_string(),
                            framework_part.to_string(),
                            ov.1.clone(),
                        ));
                        next_override = override_iter.next();
                    } else {
                        break;
                    }
                }
                // If the next override matches this bundled key,
                // emit the override body (REPLACE); otherwise emit
                // the bundled entry verbatim.
                if let Some(ov) = next_override {
                    if ov.0.as_str() == key {
                        merged.push((
                            key.to_string(),
                            lang.to_string(),
                            framework.to_string(),
                            ov.1.clone(),
                        ));
                        next_override = override_iter.next();
                        continue;
                    }
                }
                merged.push((
                    key.to_string(),
                    lang.to_string(),
                    framework.to_string(),
                    body.to_string(),
                ));
            }
            // Append any overrides whose keys sorted past every
            // bundled entry.
            while let Some(ov) = next_override {
                let (lang_part, framework_part) =
                    ov.0.split_once('/').unwrap_or((ov.0.as_str(), ""));
                merged.push((
                    ov.0.clone(),
                    lang_part.to_string(),
                    framework_part.to_string(),
                    ov.1.clone(),
                ));
                next_override = override_iter.next();
            }

            // `set` cannot fail here — the OnceLock was just
            // checked for emptiness.
            let _ = self.merged_queries.set(merged);
        }

        // Build a borrowed slice from the cached owned data. The
        // lifetime of the `&'a str` references is tied to `&self`
        // (the cached data lives in `self.merged_queries`). The
        // `Vec` is local but the references it holds are valid for
        // `'a` because the source `String`s live in `&self`.
        let cached = self
            .merged_queries
            .get()
            .expect("merged_queries was just populated above");
        let borrowed: Vec<(&'a str, &'a str, &'a str, &'a str)> = cached
            .iter()
            .map(|(k, l, f, b)| (k.as_str(), l.as_str(), f.as_str(), b.as_str()))
            .collect();
        Ok(Cow::Owned(borrowed))
    }

    /// Clone the bundled singleton into an owned [`Patterns`] so
    /// callers can layer overrides without touching the global
    /// default. `load_overrides` mutates the cloned value.
    pub fn clone_default() -> Self {
        Self::patterns().clone()
    }

    /// Build a per-repo [`Patterns`] view from `<root>/.lain/patterns/`.
    /// When the override directory is absent, returns
    /// `Cow::Borrowed(&'static Patterns)` pointing at the bundled
    /// singleton — no allocation, no clone, no override-augmented
    /// data. When overrides are present, returns
    /// `Cow::Owned(Patterns)` with the override bodies layered on.
    ///
    /// This is the canonical helper a sensor's `scan_workspace_*`
    /// calls at the top of its scan loop so the walker code can use
    /// the returned value in place of [`Self::patterns`] and observe
    /// override-augmented data. The `Cow` deref-to-`&Patterns`
    /// pattern lets every downstream consumer keep the same
    /// `&Patterns` signature they had pre-wire-in.
    ///
    /// `Err` propagates a `load_overrides` failure (malformed YAML,
    /// malformed `.scm` body, unreadable override directory).
    pub fn with_overrides(root: &Path) -> Result<Cow<'_, Patterns>, PatternsError> {
        let dir = root.join(".lain").join("patterns");
        if !dir.exists() {
            return Ok(Cow::Borrowed(Patterns::patterns()));
        }
        let mut p = Patterns::clone_default();
        p.load_overrides(root)?;
        Ok(Cow::Owned(p))
    }

    /// Look up a framework by `id` across every language.
    pub fn framework(&self, id: &str) -> Option<&FrameworkDef> {
        self.yaml
            .languages
            .values()
            .flat_map(|v| v.iter())
            .find(|f| f.id == id)
    }

    /// Mutable version of [`Self::framework`].
    fn framework_mut(&mut self, id: &str) -> Option<&mut FrameworkDef> {
        self.yaml
            .languages
            .values_mut()
            .flat_map(|v| v.iter_mut())
            .find(|f| f.id == id)
    }

    /// Iterate route frameworks for `lang` in the order the YAML
    /// listed them. `Lang::Ts` and `Lang::Tsx` share the `tsjs`
    /// bucket — the existing `http_sensor` regex does not
    /// distinguish them either.
    pub fn route_patterns(&self, lang: Lang) -> impl Iterator<Item = &FrameworkDef> {
        let key = lang_key(lang);
        self.yaml
            .languages
            .get(key)
            .into_iter()
            .flatten()
            .filter(|f| f.kind == FrameworkKind::Route)
    }

    /// Iterate outbound-call frameworks for `lang`.
    pub fn outbound_patterns(&self, lang: Lang) -> impl Iterator<Item = &FrameworkDef> {
        let key = lang_key(lang);
        self.yaml
            .languages
            .get(key)
            .into_iter()
            .flatten()
            .filter(|f| f.kind == FrameworkKind::Outbound)
    }

    /// Iterate entry-point frameworks for `lang`.
    pub fn entry_point_patterns(&self, lang: Lang) -> impl Iterator<Item = &FrameworkDef> {
        let key = lang_key(lang);
        self.yaml
            .languages
            .get(key)
            .into_iter()
            .flatten()
            .filter(|f| f.kind == FrameworkKind::EntryPoint)
    }

    /// Return the union of `deny_methods` across every outbound
    /// definition whose `lib_match` regex accepts `lib`.
    ///
    /// `_verb` is reserved for forward compatibility — Tasks 2-4 may
    /// narrow the deny surface by verb (e.g. only deny `requests.get`
    /// but not `requests.post`). Today the parameter is unused.
    ///
    /// No regex match (`lib_match` is `None`) means "any library
    /// matches"; this preserves the framework's deny surface even
    /// when the framework doesn't pin a specific library name.
    pub fn deny_methods_for(&self, lang: Lang, lib: &str, _verb: &str) -> Vec<String> {
        let key = lang_key(lang);
        let mut out = Vec::new();
        if let Some(list) = self.yaml.languages.get(key) {
            for def in list {
                if def.kind != FrameworkKind::Outbound {
                    continue;
                }
                let accepts = match def.lib_match.as_deref() {
                    None => true,
                    Some(re) => regex_match(re, lib),
                };
                if accepts {
                    out.extend(def.deny_methods.iter().cloned());
                }
            }
        }
        // Deduplicate while preserving first-seen order so callers
        // can compare against a stable list.
        let mut seen = std::collections::HashSet::new();
        out.retain(|m| seen.insert(m.clone()));
        out
    }

    /// Return the cached route-pattern [`BTreeMap`] keyed by
    /// `<lang>-<framework>`. The map is built once per `Patterns`
    /// instance (the first time this method is called) and reused
    /// on every subsequent call. The cache is invalidated on
    /// [`Self::load_overrides`] so a second load (a different
    /// `<root>/.lain/patterns/`) rebuilds the map with the new
    /// override-augmented `route_patterns(Lang)` data.
    ///
    /// Storing the cache on the `Patterns` instance (rather than a
    /// per-pointer `thread_local!` keyed on the patterns' raw
    /// address) closes the leak-across-scans bug where two
    /// consecutive scans happened to allocate their
    /// `Patterns::with_overrides` clones at the same address and
    /// the second scan inherited the first scan's override-
    /// augmented route map.
    pub fn route_patterns_map(&self) -> &BTreeMap<String, RoutePattern> {
        self.route_patterns_cache
            .get_or_init(|| build_route_patterns(self))
    }

    /// Layer per-repo overrides from `<root>/.lain/patterns/`.
    ///
    /// Transactional: a single bad body in either the YAML entries or
    /// the `.scm` files fails the whole call. The bundled registry is
    /// left untouched until every change has been validated — an
    /// operator who accidentally ships a syntax error in
    /// `<root>/.lain/patterns/rust/foo.scm` sees a single error and
    /// keeps the previous registry state.
    ///
    /// - Missing dir → no-op (`Ok(())`).
    /// - YAML entry with an existing `id` is **replaced** in-place.
    /// - YAML entry with a fresh `id` is **appended** to the
    ///   language's list (creating the language bucket if needed).
    /// - `<root>/.lain/patterns/<lang>/*.scm` are layered on top of
    ///   the bundled query map: each body is validated via
    ///   `tree_sitter::Query::new` up front. A malformed body fails
    ///   the whole call with
    ///   [`PatternsError::OverrideQuerySyntax`].
    pub fn load_overrides(&mut self, root: &Path) -> Result<(), PatternsError> {
        let dir = root.join(".lain").join("patterns");
        if !dir.exists() {
            self.overrides_applied = true;
            return Ok(());
        }

        // Step 1: validate every override `.scm` body BEFORE mutating
        // self. The collected bodies + key live in `pending_scml`
        // until we know every one of them parses against its grammar.
        let mut pending_scml: Vec<(String, String)> = Vec::new();
        for lang_dir in walk_lang_dirs(&dir)? {
            let read_dir = match std::fs::read_dir(&lang_dir) {
                Ok(d) => d,
                Err(e) => {
                    return Err(PatternsError::OverrideRead {
                        path: lang_dir.clone(),
                        source: e,
                    })
                }
            };
            for entry in read_dir.flatten() {
                let path = entry.path();
                if path.extension().and_then(|e| e.to_str()) != Some("scm") {
                    continue;
                }
                let stem = path
                    .file_name()
                    .and_then(|n| n.to_str())
                    .unwrap_or_else(|| panic!("invalid .scm path: {}", path.display()))
                    .to_string();
                let lang_yaml = lang_dir
                    .file_name()
                    .and_then(|n| n.to_str())
                    .unwrap_or("unknown")
                    .to_string();
                let key = format!("{lang_yaml}/{stem}");
                let body =
                    std::fs::read_to_string(&path).map_err(|e| PatternsError::OverrideRead {
                        path: path.clone(),
                        source: e,
                    })?;
                validate_scm_body(&key, &body)?;
                pending_scml.push((key, body));
            }
        }

        // `read_dir` order is platform-dependent. `compiled_queries`
        // assumes the override list is sorted by key (its merge loop
        // walks `override_scml` and the bundled entries in lock-step
        // using key ordering — unsorted overrides would skip the
        // "advance past sorted overrides" emit branch and either
        // duplicate entries or miss replacements). Sort here so
        // every later consumer sees a stable, ordered view.
        pending_scml.sort_by(|a, b| a.0.cmp(&b.0));

        // Step 2: parse + apply. Validation here only catches YAML
        // structure errors; the `.scm` validation already ran above.
        let overrides = YamlFile::load_from_dir(&dir)?;
        for (lang, list) in overrides.languages {
            for new_def in list {
                if let Some(existing) = self.framework_mut(&new_def.id) {
                    *existing = new_def;
                } else {
                    self.yaml
                        .languages
                        .entry(lang.clone())
                        .or_default()
                        .push(new_def);
                }
            }
        }
        // Populate the override cache. Bodies were validated above
        // (Step 1); the cache is a plain `Vec` so the second-call
        // behaviour is **all-or-nothing**: a subsequent
        // `load_overrides` on the same `Patterns` instance legitimately
        // re-loads — old bodies are dropped, new bodies take their
        // place. The walker code is single-threaded per scan, so the
        // cache mutation is contained to the calling scan; concurrent
        // scans from different threads each hold their own `Patterns`
        // clone.
        self.override_scml = pending_scml;

        // Invalidate the cached merged queries so the next
        // `compiled_queries()` call rebuilds with the new override
        // bodies. Without this invalidation, a second
        // `load_overrides` on the same `Patterns` instance leaves a
        // stale cache (the first-load bodies, not the second-load
        // bodies), which is the bug the third regression test
        // (`second_load_overrides_call_invalidates_merged_cache`)
        // pins.
        self.merged_queries = OnceLock::new();

        // The route-patterns cache is built from
        // `self.yaml.languages` (the override-augmented YAML
        // registry). A new `load_overrides` call that replaces a
        // route framework's YAML entry must invalidate the cache so
        // the next `route_patterns_map()` call rebuilds with the
        // override's data. The brief pins this on bug 1's
        // regression surface — without invalidation, a repo that
        // re-overrides a framework's regex would still see the
        // bundled regex.
        self.route_patterns_cache = OnceLock::new();

        self.overrides_applied = true;
        Ok(())
    }

    /// `true` once [`Self::load_overrides`] has run, regardless of
    /// whether it merged anything. Useful for diagnostics.
    pub fn overrides_applied(&self) -> bool {
        self.overrides_applied
    }
}

/// What failed during a Patterns operation. The brief requires a
/// *structured* error for malformed YAML — `serde_yaml::Error` carries
/// line / column info.
#[derive(Debug, thiserror::Error)]
pub enum PatternsError {
    #[error("malformed frameworks YAML: {0}")]
    Yaml(#[from] serde_yaml::Error),
    #[error("could not read override directory {path:?}: {source}")]
    OverrideRead {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("invalid tree-sitter query in override .scm file {path:?}: {message} (row {row}, column {column})")]
    OverrideQuerySyntax {
        path: String,
        row: usize,
        column: usize,
        message: String,
    },
}

/// Validate a `.scm` body against the grammar registered for its
/// `<lang>/` bucket prefix. Bundled bodies go through the same
/// `tree_sitter::Query::new` call in `patterns/build.rs` at build
/// time, so this is the runtime second leg for override bodies.
///
/// `key` is the `<lang>/<framework>.scm` form (or any labelled
/// string the caller wants surfaced on error). The grammar lookup
/// mirrors `src/server/sensors/util.rs::grammar_for` so a runtime
/// panic and a build-time panic name the same grammar.
fn validate_scm_body(key: &str, body: &str) -> Result<(), PatternsError> {
    let (lang_yaml, _) = key
        .split_once('/')
        .ok_or_else(|| PatternsError::OverrideQuerySyntax {
            path: key.to_string(),
            row: 0,
            column: 0,
            message: "expected key of the form '<lang>/<framework>.scm'".to_string(),
        })?;
    let grammar =
        grammar_for_yaml_key(lang_yaml).ok_or_else(|| PatternsError::OverrideQuerySyntax {
            path: key.to_string(),
            row: 0,
            column: 0,
            message: format!("no tree-sitter grammar registered for lang bucket {lang_yaml:?}"),
        })?;
    tree_sitter::Query::new(&grammar, body)
        .map(|_| ())
        .map_err(|e| PatternsError::OverrideQuerySyntax {
            path: key.to_string(),
            row: e.row,
            column: e.column,
            message: format!("{}: {}", query_error_kind_str(&e.kind), e.message),
        })
}

/// Resolve a tree-sitter [`tree_sitter::Language`] for the language
/// bucket key (`rust`, `python`, `tsjs`, …). Mirrors
/// `src/server/sensors/util.rs::grammar_for` so a runtime panic
/// names the same grammar as the build-time validator.
fn grammar_for_yaml_key(lang_yaml: &str) -> Option<tree_sitter::Language> {
    use crate::server::sensors::util::language_for;
    let lang = match lang_yaml {
        "rust" => Some(Lang::Rust),
        "python" => Some(Lang::Python),
        "tsjs" => Some(Lang::TsJs),
        "go" => Some(Lang::Go),
        "java" => Some(Lang::Java),
        "csharp" => Some(Lang::CSharp),
        "ruby" => Some(Lang::Ruby),
        "kotlin" => Some(Lang::Kotlin),
        // `ts` / `tsx` directories are not currently emitted by the
        // override walker (the bundled patterns split TypeScript and
        // JavaScript under a single `tsjs/` bucket) but the route is
        // reserved for a future expansion.
        "ts" => Some(Lang::Ts),
        "tsx" => Some(Lang::Tsx),
        _ => None,
    }?;
    Some(language_for(lang))
}

/// Walk `<root>/<lang>/` directories and return them. Mirrors
/// `patterns/build.rs::discover_lang_dirs` for the runtime override
/// path so an org's `<root>/.lain/patterns/rust/axum-route.scm`
/// shadows the bundled `axum-route.scm`.
fn walk_lang_dirs(root: &Path) -> Result<Vec<PathBuf>, PatternsError> {
    let read_dir = std::fs::read_dir(root).map_err(|e| PatternsError::OverrideRead {
        path: root.to_path_buf(),
        source: e,
    })?;
    let mut langs: Vec<PathBuf> = read_dir
        .filter_map(Result::ok)
        .filter(|e| e.path().is_dir())
        .filter(|e| !e.file_name().to_string_lossy().starts_with('.'))
        .map(|e| e.path())
        .collect();
    langs.sort();
    Ok(langs)
}

/// Render a [`tree_sitter::QueryErrorKind`] as a stable human label
/// so the structured error surfaces the failure class (`Syntax`,
/// `NodeType`, …). Mirrors the labels `tree-sitter`'s own `Display`
/// uses; we spell them out explicitly rather than depending on tree-
/// sitter's Display implementation which couples to the source preview
/// layout.
fn query_error_kind_str(kind: &tree_sitter::QueryErrorKind) -> &'static str {
    use tree_sitter::QueryErrorKind;
    match kind {
        QueryErrorKind::Syntax => "Invalid syntax",
        QueryErrorKind::NodeType => "Invalid node type",
        QueryErrorKind::Field => "Invalid field name",
        QueryErrorKind::Capture => "Invalid capture name",
        QueryErrorKind::Predicate => "Invalid predicate",
        QueryErrorKind::Structure => "Impossible pattern",
        QueryErrorKind::Language => "Language mismatch",
    }
}

/// Map a [`Lang`] to the YAML bucket key. `Ts` and `Tsx` share the
/// `tsjs` bucket because the existing `http_sensor` /
/// `http_client_sensor` walkers treat them uniformly.
fn lang_key(lang: Lang) -> &'static str {
    match lang {
        Lang::Python => "python",
        Lang::TsJs | Lang::Ts | Lang::Tsx => "tsjs",
        Lang::Rust => "rust",
        Lang::Go => "go",
        Lang::Java => "java",
        Lang::CSharp => "csharp",
        Lang::Ruby => "ruby",
        Lang::Kotlin => "kotlin",
    }
}

/// Match `lib` against `pattern` as a regex. Compiled on every call —
/// `lib_match` is small (5-10 chars per definition) and `deny_methods_for`
/// is on the cold path; a `OnceLock<Regex>` cache would be premature
/// optimisation.
fn regex_match(pattern: &str, lib: &str) -> bool {
    match regex::Regex::new(pattern) {
        Ok(re) => re.is_match(lib),
        // A malformed regex would be a load-time bug, not a runtime
        // one. The bundled YAML is exercised by tests, so a malformed
        // entry surfaces immediately.
        Err(_) => false,
    }
}

// ─── RoutePattern (http_sensor walker) ────────────────────────────
//
// `RoutePattern` lived in `http_sensor.rs` historically, but the
// runtime-override wire-in (this PR) moved the build-and-cache surface
// onto `Patterns` itself so the cache is per-instance (and therefore
// cannot leak across scans that happen to allocate a fresh
// `Patterns::with_overrides` at the same address as a previous
// scan's). The struct and its builders live here for that reason;
// the `extract` method that consumes the per-line text and emits
// `HttpRoute` records stays in `http_sensor.rs` (it depends on
// `HttpRoute`, which is a sensor-local type).

/// HTTP route patterns per language
pub struct RoutePattern {
    /// `None` for APIs that carry no verb at the call site (Go's
    /// `http.HandleFunc`). Per §6.2 these routes are emitted as
    /// `HttpMethod::Any` (was `GET` in 0.8).
    method_regex: Option<regex::Regex>,
    path_regex: regex::Regex,
    handler_fn_regex: regex::Regex,
    /// What to emit when the regex above did not capture a verb.
    /// `HttpMethod::Any` for go-std (the route declares no verb);
    /// `HttpMethod::Get` for Flask (whose default verb is GET even
    /// when `methods=` is absent, §6.2).
    default_method: HttpMethod,
}

impl RoutePattern {
    pub fn default_method(&self) -> HttpMethod {
        self.default_method
    }
    pub fn path_regex(&self) -> &regex::Regex {
        &self.path_regex
    }
    pub fn method_regex(&self) -> Option<&regex::Regex> {
        self.method_regex.as_ref()
    }
    pub fn handler_fn_regex(&self) -> &regex::Regex {
        &self.handler_fn_regex
    }
}

/// Stable map key for a (lang, framework) pair. Mirrors the inline
/// table's `<lang-prefix>-<framework-tail>` shape so existing call
/// sites (tests, the `prefixes` slice in `scan_file_for_routes`)
/// keep matching.
///
/// Returns `String` (was `&'static str` with `Box::leak`); the
/// lifetime-tightening pass removed the leak so the keys borrow
/// from the cache on the `Patterns` instance.
fn route_pattern_key(lang: Lang, def: &FrameworkDef) -> String {
    let prefix = match lang {
        Lang::Rust => "rust",
        Lang::Python => "python",
        Lang::TsJs | Lang::Ts | Lang::Tsx => "tsjs",
        Lang::Go => "go",
        Lang::Java => "java",
        Lang::CSharp => "csharp",
        Lang::Ruby => "ruby",
        Lang::Kotlin => "kotlin",
    };
    format!("{prefix}-{}", def.id)
}

/// Build a [`RoutePattern`] for one `FrameworkDef` from the bundled
/// YAML, layering framework-specific regex overrides that the YAML
/// schema can't encode (Flask's `methods=["POST"]` kwarg, the
/// verbless `http.HandleFunc` shape, etc.).
///
/// Contract:
///   - `Some(_)` is returned when `def.path_regex` is present; the
///     walker has something to match against and the framework is
///     emitted as a candidate route pattern.
///   - `None` is returned when `def.path_regex` is missing — the
///     walker has nothing to match against, and the framework is
///     silently skipped (the same was true of the pre-Task-2 inline
///     table: frameworks without a path regex just weren't listed).
///
/// Fields read from [`FrameworkDef`]:
///   - `def.path_regex` — the route-template regex; panics at
///     construction if it fails to compile (so a malformed YAML entry
///     crashes the binary loudly rather than corrupting the walker).
///   - `def.handler_regex` — captured by [`handler_regex_for`]; for
///     most frameworks it's used as-is, but Sinatra / Minimal API /
///     Rails need a framework-specific override (the YAML's regex
///     lost a capture group during the Task-1 data conversion).
///   - `def.verbs` — joined into a `(verb|verb|verb)` alternation
///     inside [`method_capture_for`] to build `method_regex`. The
///     escape order is the YAML's verbatim order, so framework ids
///     that put `GET` / `POST` first in `verbs` match `GET` before
///     `POST`.
///
/// The returned `RoutePattern`'s `default_method` is the framework's
/// verb when the method regex is unambiguous (`HttpMethod::Get` for
/// "verbed" frameworks) and `HttpMethod::Any` when the framework
/// admits any HTTP verb or has an empty `verbs:` list (verbless
/// APIs like Go-std `HandleFunc`).
fn route_pattern_for(def: &FrameworkDef) -> Option<RoutePattern> {
    let path_re = def.path_regex.as_deref()?;
    let handler_re = handler_regex_for(def);

    let (method_re, default) = method_capture_for(def);

    let path_regex = regex::Regex::new(path_re)
        .unwrap_or_else(|e| panic!("{}: invalid path_regex {:?}: {e}", def.id, path_re));
    let handler_fn_regex = regex::Regex::new(handler_re)
        .unwrap_or_else(|e| panic!("{}: invalid handler_regex {:?}: {e}", def.id, handler_re));
    let method_regex = method_re.map(|s| {
        regex::Regex::new(s)
            .unwrap_or_else(|e| panic!("{}: invalid method_regex {:?}: {e}", def.id, s))
    });

    Some(RoutePattern {
        method_regex,
        path_regex,
        handler_fn_regex,
        default_method: default,
    })
}

/// Resolve the handler-capture regex for `def`. Returns the YAML's
/// `handler_regex` when it has a useful capture group, or a
/// framework-specific override when the YAML regex was simplified
/// (the original inline regex had capture groups the YAML lost in
/// Task 1's data conversion).
///
/// Each `Box::leak` here is bounded — one per framework per
/// `route_pattern_for` call, which itself runs once per
/// `Patterns::route_patterns_map` build (cached thereafter). The
/// leak is not per-scan.
fn handler_regex_for(def: &FrameworkDef) -> &'static str {
    match def.id.as_str() {
        // Sinatra — the inline regex captured the verb on the
        // declaring line as the handler name (`Sinatra__do_block`
        // per the §6.2 comment). YAML's `do\s*$` has no capture.
        "sinatra-route" => {
            Box::leak(
                r#"(?m)^[ \t]*(get|post|put|delete|patch|options|head)\s+['"][^'"]+['"]"#
                    .to_string()
                    .into_boxed_str(),
            )
        }
        // Minimal API — the inline regex captured the entire
        // quoted path (group 1 = `"/api/health"`). YAML's
        // simplified regex has no capture group; we restore the
        // capture here so the `RoutePattern::extract` look-ahead
        // finds a non-empty handler name on the same line.
        "minimal-api-route" => {
            Box::leak(
                r#"\.(?:MapGet|MapPost|MapPut|MapDelete|MapPatch)\s*\(\s*(['"][^'"]+['"])\s*,\s*(?:async\s*)?\([^)]*\)\s*=>"#
                    .to_string()
                    .into_boxed_str(),
            )
        }
        // Rails — no handler_regex in YAML; capture the verb (or
        // the word following the path) as the handler.
        "rails-route" => {
            Box::leak(
                r"(?m)^[ \t]*(get|post|put|patch|delete|options|head|resources)\b"
                    .to_string()
                    .into_boxed_str(),
            )
        }
        // Default — use the YAML's handler_regex as-is, or fall
        // back to a word-boundary placeholder that captures any
        // identifier on the line.
        _ => Box::leak(
            def.handler_regex
                .as_deref()
                .unwrap_or(r"\b\w+\b")
                .to_string()
                .into_boxed_str(),
        ),
    }
}

/// Per-framework `method_regex` + `default_method`. The YAML's
/// `verbs` field drives the verb list; the surrounding syntax is
/// framework-specific and lives here. Returns `None` for verbless
/// APIs (Go-std `HandleFunc`) — those default to
/// [`HttpMethod::Any`] per §6.2.
///
/// Each `Box::leak` here is bounded — one per framework per
/// `route_pattern_for` call (see `handler_regex_for`).
fn method_capture_for(def: &FrameworkDef) -> (Option<&'static str>, HttpMethod) {
    let verbs = def.verbs.join("|");
    match def.id.as_str() {
        // Flask — the verb lives in `methods=["POST"]`, not in the
        // `@app.route("/…")` decorator.
        "flask-route" => (Some(r#"methods\s*=\s*\[\s*["'](\w+)"#), HttpMethod::Get),
        // Go stdlib — `http.HandleFunc` declares no verb at the
        // call site; routes emit `HttpMethod::Any`.
        "stdlib-http-route" => (None, HttpMethod::Any),
        // Kotlin — `routing { get("/path") { … } }` puts the verb
        // before the parenthesised path.
        "ktor-route" => (
            Some(Box::leak(
                format!(r"(?m)(?:^|\W)({verbs})\s*\(").into_boxed_str(),
            )),
            HttpMethod::Any,
        ),
        // Rails — `get 'path' do … end` style. The verb may be
        // followed by a quote (path), a colon (resources), or
        // whitespace.
        "rails-route" => (
            Some(Box::leak(
                format!(r#"(?i:({verbs}))['"\s:]+"#).into_boxed_str(),
            )),
            HttpMethod::Any,
        ),
        // C# Minimal API — the verb is baked into `MapGet` /
        // `MapPost` etc., not a separate token.
        "minimal-api-route" => (
            Some(r"\.(?i:(MapGet|MapPost|MapPut|MapDelete|MapPatch))"),
            HttpMethod::Any,
        ),
        // C# ASP.NET controllers — `[HttpGet]` etc. with the verb
        // baked into the attribute name.
        "aspnet-route" => (
            Some(Box::leak(format!(r"(?i:\[Http({verbs}))").into_boxed_str())),
            HttpMethod::Any,
        ),
        // JAX-RS — `@GET` / `@POST` on its own line, just above
        // the method declaration.
        "jaxrs-route" => (
            Some(Box::leak(format!(r"@(?i:({verbs}))\s*$").into_boxed_str())),
            HttpMethod::Any,
        ),
        // Spring — `@GetMapping` / `@PostMapping` / etc.
        "spring-route" => (
            Some(Box::leak(
                format!(r"@(?i:({verbs}))Mapping").into_boxed_str(),
            )),
            HttpMethod::Any,
        ),
        // axum — `.route("/path", get(handler))` — verb appears
        // as the second argument to `.route()`.
        "axum-route" => (
            Some(Box::leak(
                format!(r"\.route\s*\([^,]*,\s*(?i:({verbs}))\s*\(").into_boxed_str(),
            )),
            HttpMethod::Any,
        ),
        // actix-web — `#[get("/path")]` attribute on a function.
        "actix-route" => (
            Some(Box::leak(
                format!(r"#\[(?i:({verbs}))\s*\(").into_boxed_str(),
            )),
            HttpMethod::Any,
        ),
        // FastAPI — `@app.get("/path")` decorator.
        "fastapi-route" => (
            Some(Box::leak(
                format!(r"@[\w\.]+\.({verbs})\s*\(").into_boxed_str(),
            )),
            HttpMethod::Any,
        ),
        // Sinatra — `get '/path' do … end`.
        "sinatra-route" => (
            Some(Box::leak(
                format!(r#"(?i:({verbs}))\s+['"]"#).into_boxed_str(),
            )),
            HttpMethod::Any,
        ),
        // Gin / Echo — `r.GET("/path", handler)`. The verb is
        // uppercase at the call site (verbs in the YAML are
        // already uppercase).
        "gin-route" => (
            Some(Box::leak(format!(r"\.({verbs})\s*\(").into_boxed_str())),
            HttpMethod::Any,
        ),
        // Express / Fastify — `router.post("/path", handler)`.
        "express-route" | "fastify-route" => (
            Some(Box::leak(format!(r"\.({verbs})\s*\(").into_boxed_str())),
            HttpMethod::Any,
        ),
        // Unknown framework — leave the method regex unset and
        // rely on `default_method`. Future frameworks opt in by
        // adding a match arm above.
        _ => (None, HttpMethod::Any),
    }
}

/// Build the route-pattern `BTreeMap` for the given `registry`. The
/// map is keyed by `<lang>-<framework>` and stores a `RoutePattern`
/// per route framework the registry knows about. Iteration order
/// is sorted by key (`BTreeMap` §6.1) so the §8.3 determinism
/// contract holds across runs.
fn build_route_patterns(registry: &Patterns) -> BTreeMap<String, RoutePattern> {
    let mut patterns = BTreeMap::new();

    let langs: [Lang; 8] = [
        Lang::Rust,
        Lang::Python,
        Lang::TsJs,
        Lang::Go,
        Lang::Java,
        Lang::CSharp,
        Lang::Ruby,
        Lang::Kotlin,
    ];

    for lang in langs {
        for def in registry.route_patterns(lang) {
            let Some(rp) = route_pattern_for(def) else {
                continue;
            };
            let key = route_pattern_key(lang, def);
            patterns.insert(key, rp);
        }
    }

    patterns
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lang_key_handles_every_variant() {
        // Pin the mapping — `lang_key` is the contract between the
        // YAML keys and the `Lang` enum. Drift here is silent
        // (returns an empty iterator) but breaks every sensor.
        assert_eq!(lang_key(Lang::Python), "python");
        assert_eq!(lang_key(Lang::TsJs), "tsjs");
        assert_eq!(lang_key(Lang::Ts), "tsjs");
        assert_eq!(lang_key(Lang::Tsx), "tsjs");
        assert_eq!(lang_key(Lang::Rust), "rust");
        assert_eq!(lang_key(Lang::Go), "go");
        assert_eq!(lang_key(Lang::Java), "java");
        assert_eq!(lang_key(Lang::CSharp), "csharp");
        assert_eq!(lang_key(Lang::Ruby), "ruby");
        assert_eq!(lang_key(Lang::Kotlin), "kotlin");
    }
}
